"""Extraction and rendering for docs/generated/: pure over the files it reads.

`generate(root)` returns the four files as {relative path: text}; `write`
and `stale` compare that with what is on disk. Parsing failures raise
`GenDocsError` naming file and line, so a typo never silently drops an entry.
"""

from __future__ import annotations

import ast
import re
import tomllib
from dataclasses import dataclass
from pathlib import Path

HEADER = "<!-- Generated by metalm-gendocs from the code. Do not edit; change the docstring or test instead. -->\n\n"
OWNER_MARK = "(owner)"
SECTION_RE = re.compile(r"^(Decisions|Terms):\s*$")
NEVER_IMPORTS_RE = re.compile(r"^Never imports:\s*(.+)$")
TERM_RE = re.compile(r"^\*\*(?P<term>[^*]+)\*\*:\s*(?P<definition>.+)$", re.S)
NODE_EXTS = (".ts", ".tsx", ".js", ".mjs", ".cjs")
NODE_TEST_RE = re.compile(r"\.(test|spec)\.(ts|tsx|js|mjs|cjs)$")
JSDOC_RE = re.compile(r"/\*\*(.*?)\*/", re.S)
CUJ_COMMENT_RE = re.compile(r"^\s*//\s*cuj:\s*(?P<journey>.+?)\s*$")
NODE_TEST_CALL_RE = re.compile(r"""^\s*(?:test|it)(?:\.\w+)?\(\s*(['"`])(?P<name>.+?)\1""")
RUST_FN_RE = re.compile(r"^\s*(?:pub(?:\([^)]*\))?\s+)?(?:async\s+)?fn\s+(?P<name>\w+)")
RUST_ROOT_STEMS = {"lib", "mod"}  # the file is its folder's module; main.rs keeps its own name
# Languages metalm-gendocs does not read yet: extension -> name shown in index.md.
UNCOVERED = {".swift": "Swift", ".go": "Go", ".kt": "Kotlin", ".java": "Java", ".rb": "Ruby", ".cs": "C#", ".cpp": "C++", ".c": "C"}
SKIP_DIRS = {"__pycache__", "node_modules", ".venv", "build", "dist", ".git", "target"}


class GenDocsError(Exception):
    """A docstring or marker the generator cannot read; the message names file and line."""


@dataclass(frozen=True, slots=True)
class Config:
    src: str = "src"
    tests: str = "tests"
    out: str = "docs/generated"
    roots: tuple[str, ...] = ()  # extra source roots, walked like src; their modules are named by path


@dataclass(frozen=True, slots=True)
class Area:
    name: str
    path: str
    purpose: str
    never_imports: str


@dataclass(frozen=True, slots=True)
class Entry:
    """One bullet under Decisions: or Terms:, with where it came from."""

    module: str
    path: str
    text: str


@dataclass(frozen=True, slots=True)
class Cuj:
    journey: str
    test_id: str


def load_config(root: Path) -> Config:
    pyproject = root / "pyproject.toml"
    if not pyproject.exists():
        return Config()
    table = tomllib.loads(pyproject.read_text()).get("tool", {}).get("metalm-gendocs", {})
    known = set(Config.__dataclass_fields__)
    unknown = sorted(set(table) - known)
    if unknown:
        raise GenDocsError(f"pyproject.toml [tool.metalm-gendocs]: unknown key(s) {', '.join(unknown)}; known: {', '.join(sorted(known))}")
    for key, value in table.items():
        if key == "roots":
            if not (isinstance(value, list) and all(isinstance(v, str) for v in value)):
                raise GenDocsError("pyproject.toml [tool.metalm-gendocs].roots must be a list of strings")
            table[key] = tuple(value)
        elif not isinstance(value, str):
            raise GenDocsError(f"pyproject.toml [tool.metalm-gendocs].{key} must be a string")
    return Config(**table)


def _docstring(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(), filename=str(path))
    except SyntaxError as exc:
        raise GenDocsError(f"{path}:{exc.lineno}: cannot parse: {exc.msg}") from exc
    return ast.get_docstring(tree, clean=True) or ""


def _jsdoc(path: Path) -> str:
    """The `@packageDocumentation` block, else a JSDoc block that opens the file; cleaned like a docstring."""
    text = path.read_text()
    blocks = list(JSDOC_RE.finditer(text))
    chosen = next((b for b in blocks if "@packageDocumentation" in b.group(1)), None)
    if chosen is None and blocks and not text[: blocks[0].start()].strip().lstrip("#!").strip():
        chosen = blocks[0]
    if chosen is None:
        return ""
    lines = []
    for line in chosen.group(1).splitlines():
        line = re.sub(r"^\s*\* ?", "", line)
        if line.strip() != "@packageDocumentation":
            lines.append(line.rstrip())
    return "\n".join(lines).strip()


def _rustdoc(path: Path) -> str:
    """The `//!` inner doc comment that opens the file (inner attributes and blank lines may sit among it)."""
    lines = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("//!"):
            lines.append(re.sub(r"^ ", "", stripped[3:]).rstrip())
        elif stripped and not stripped.startswith("#!["):
            break
    return "\n".join(lines).strip()


def _walk(root: Path, exts: tuple[str, ...]) -> list[Path]:
    if not root.is_dir():
        return []
    return sorted(p for p in root.rglob("*") if p.suffix in exts and p.is_file() and not SKIP_DIRS & set(p.parts))


def _module_name(src_root: Path, path: Path) -> str:
    parts = list(path.relative_to(src_root).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _paragraph_one(doc: str) -> str:
    first = doc.strip().split("\n\n", 1)[0]
    return " ".join(first.split())


def _sections(doc: str) -> dict[str, list[str]]:
    """Bullets under each `Decisions:`/`Terms:` header; continuation lines join the bullet above."""
    out: dict[str, list[str]] = {}
    current: list[str] | None = None
    for line in doc.splitlines():
        stripped = line.strip()
        header = SECTION_RE.match(stripped)
        if header:
            current = out.setdefault(header.group(1), [])
        elif current is None:
            continue
        elif stripped.startswith("- "):
            current.append(stripped[2:].strip())
        elif stripped and current and line.startswith((" ", "\t")):
            current[-1] += " " + stripped
        else:
            current = None
    return out


def _in_node_project(root: Path, path: Path) -> bool:
    """A Node file is read when a package.json sits in its folder or any folder above it, up to the repo root."""
    for folder in path.parents:
        if (folder / "package.json").is_file():
            return True
        if folder == root:
            return False
    return False


def _source_roots(root: Path, cfg: Config) -> list[Path]:
    return [root / cfg.src] + [root / extra for extra in cfg.roots]


def _sources(root: Path, cfg: Config) -> list[tuple[Path, Path]]:
    """(source root, file) for Python files, Rust files, and Node files inside a Node project; tests excluded."""
    found = []
    for base in _source_roots(root, cfg):
        found += [(base, p) for p in _walk(base, (".py", ".rs"))]
        found += [(base, p) for p in _walk(base, NODE_EXTS) if not NODE_TEST_RE.search(p.name) and _in_node_project(root, p)]
    return sorted(found, key=lambda pair: pair[1])


def _is_area(src_root: Path, path: Path) -> bool:
    rel = path.relative_to(src_root).parts
    if path.suffix == ".py":
        return path.name == "__init__.py" or len(rel) == 2
    if path.suffix == ".rs":
        return path.stem in RUST_ROOT_STEMS | {"main"} or len(rel) == 1
    return path.stem == "index" or len(rel) == 1


def _node_module_name(src_root: Path, path: Path) -> str:
    """Path-style name for Node and Rust files: `index` (Node), `lib` and `mod` (Rust) name their folder."""
    parts = list(path.relative_to(src_root).with_suffix("").parts)
    folder_stems = RUST_ROOT_STEMS if path.suffix == ".rs" else {"index"}
    if parts[-1] in folder_stems:
        parts.pop()
    return "/".join(parts) or "(root)"


def _name(root: Path, cfg: Config, src_root: Path, path: Path) -> str:
    """Module name: dotted for Python, path-style for Node and Rust; in an extra root, prefixed by that root's path."""
    if src_root != root / cfg.src:
        name = _node_module_name(src_root, path)
        base = src_root.relative_to(root).as_posix()
        return base if name == "(root)" else f"{base}/{name}"
    return _module_name(src_root, path) if path.suffix == ".py" else _node_module_name(src_root, path)


def _cuj_journey(decorator: ast.expr) -> ast.expr | None:
    """The journey argument when `decorator` is `pytest.mark.cuj(...)` or `mark.cuj(...)`; else None."""
    if not isinstance(decorator, ast.Call):
        return None
    func = decorator.func
    if not (isinstance(func, ast.Attribute) and func.attr == "cuj"):
        return None
    base = func.value
    if not (isinstance(base, ast.Attribute) and base.attr == "mark") and not (isinstance(base, ast.Name) and base.id == "mark"):
        return None
    return decorator.args[0] if decorator.args else ast.Constant(None)


def _cujs(root: Path, cfg: Config) -> list[Cuj]:
    tests_root = root / cfg.tests
    if not tests_root.is_dir():
        return []
    found: list[Cuj] = []
    for path in sorted(p for p in tests_root.rglob("test_*.py") if "__pycache__" not in p.parts):
        rel = path.relative_to(root).as_posix()
        try:
            tree = ast.parse(path.read_text(), filename=rel)
        except SyntaxError as exc:
            raise GenDocsError(f"{rel}:{exc.lineno}: cannot parse: {exc.msg}") from exc

        def visit(nodes: list[ast.stmt], prefix: str) -> None:
            for node in nodes:
                if isinstance(node, ast.ClassDef):
                    visit(node.body, f"{prefix}::{node.name}")
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    continue
                for decorator in node.decorator_list:
                    arg = _cuj_journey(decorator)
                    if arg is None:
                        continue
                    if not (isinstance(arg, ast.Constant) and isinstance(arg.value, str) and arg.value.strip()):
                        raise GenDocsError(f"{rel}:{decorator.lineno}: cuj marker needs the journey as a plain string")
                    found.append(Cuj(" ".join(arg.value.split()), f"{prefix}::{node.name}"))

        visit(tree.body, rel)
    return sorted(found, key=lambda c: (c.test_id, c.journey))


def _comment_cujs(root: Path, cfg: Config) -> list[Cuj]:
    """`// cuj: <journey>` above a Node `test(...)`/`it(...)` call, or above a Rust `#[test]` fn."""
    bases = [root / cfg.tests] + _source_roots(root, cfg)
    node = {p for base in bases for p in _walk(base, NODE_EXTS) if NODE_TEST_RE.search(p.name) and _in_node_project(root, p)}
    rust = {p for base in bases for p in _walk(base, (".rs",))}
    return _node_cujs(root, node) + _rust_cujs(root, rust)


def _rust_cujs(root: Path, files: set[Path]) -> list[Cuj]:
    found: list[Cuj] = []
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        lines = path.read_text().splitlines()
        for number, line in enumerate(lines, 1):
            match = CUJ_COMMENT_RE.match(line)
            if not match:
                continue
            following = [text.strip() for text in lines[number:] if text.strip()]
            attrs = []
            while following and following[0].startswith("#["):
                attrs.append(following.pop(0))
            fn = RUST_FN_RE.match(following[0]) if following else None
            if fn is None or not any(re.fullmatch(r"#\[(?:\w+::)*test\]", a) for a in attrs):
                raise GenDocsError(f"{rel}:{number}: '// cuj:' must sit above a #[test] fn")
            found.append(Cuj(" ".join(match.group("journey").split()), f"{rel}::{fn.group('name')}"))
    return found


def _node_cujs(root: Path, files: set[Path]) -> list[Cuj]:
    found: list[Cuj] = []
    for path in sorted(files):
        rel = path.relative_to(root).as_posix()
        lines = path.read_text().splitlines()
        for number, line in enumerate(lines, 1):
            match = CUJ_COMMENT_RE.match(line)
            if not match:
                continue
            following = next((text for text in lines[number:] if text.strip()), "")
            call = NODE_TEST_CALL_RE.match(following)
            if call is None:
                raise GenDocsError(f"{rel}:{number}: '// cuj:' must sit on the line above a test(...) or it(...) call with a string name")
            found.append(Cuj(" ".join(match.group("journey").split()), f"{rel}::{call.group('name')}"))
    return found


def _uncovered(root: Path, cfg: Config) -> dict[str, int]:
    """Source and test files in languages the generator does not read: name -> file count."""
    counts: dict[str, int] = {}
    for base in [root / cfg.tests] + _source_roots(root, cfg):
        for path in _walk(base, tuple(UNCOVERED)):
            counts[UNCOVERED[path.suffix]] = counts.get(UNCOVERED[path.suffix], 0) + 1
    return counts


def _extract(root: Path, cfg: Config) -> tuple[list[Area], list[Entry], list[Entry]]:
    areas: list[Area] = []
    decisions: list[Entry] = []
    terms: list[Entry] = []
    for src_root, path in _sources(root, cfg):
        doc = {".py": _docstring, ".rs": _rustdoc}.get(path.suffix, _jsdoc)(path)
        module = _name(root, cfg, src_root, path)
        rel = path.relative_to(root).as_posix()
        if _is_area(src_root, path):
            never = ""
            lines = doc.splitlines()
            for number, line in enumerate(lines):
                match = NEVER_IMPORTS_RE.match(line.strip())
                if match:
                    parts = [match.group(1).strip()]
                    for following in lines[number + 1 :]:  # wrapped continuation lines are indented
                        if not following.strip() or not following.startswith((" ", "\t")):
                            break
                        parts.append(following.strip())
                    never = " ".join(parts)
            areas.append(Area(module, rel, _paragraph_one(doc), never))
        sections = _sections(doc)
        decisions += [Entry(module, rel, text) for text in sections.get("Decisions", [])]
        for text in sections.get("Terms", []):
            if not TERM_RE.match(text):
                raise GenDocsError(f"{rel}: Terms entry must read '- **term**: definition', got: {text[:60]}")
            terms.append(Entry(module, rel, text))
    return areas, decisions, terms


def _render_index(areas: list[Area], uncovered: dict[str, int]) -> str:
    lines = ["# Areas", ""]
    if uncovered:
        listed = ", ".join(f"{name} ({count} files)" for name, count in sorted(uncovered.items()))
        lines += [
            "## Not covered",
            "",
            f"metalm-gendocs reads Python, Rust and TypeScript/JavaScript only; it skipped {listed}.",
            "Agent: ask the owner whether to add each language to metalm-gendocs; on yes, file a metalm issue naming its doc-comment convention, test framework and this repo.",
            "",
        ]
    if not areas:
        lines.append("None yet: no packages under the source root.")
    for area in sorted(areas, key=lambda a: a.name):
        lines += [f"## `{area.name}`", "", f"`{area.path}`", "", area.purpose or "_No docstring._", ""]
        if area.never_imports:
            lines += [f"Never imports: {area.never_imports}", ""]
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_decisions(entries: list[Entry]) -> str:
    owner = [e for e in entries if e.text.rstrip().endswith(OWNER_MARK)]
    drafted = [e for e in entries if not e.text.rstrip().endswith(OWNER_MARK)]
    lines = ["# Decisions", "", "Rules that span modules, from each package's `Decisions:`. Owner rules end with `(owner)`.", ""]
    for title, group in (("Owner", owner), ("Agent-drafted", drafted)):
        lines += [f"## {title}", ""]
        if not group:
            lines += ["None yet.", ""]
        for entry in sorted(group, key=lambda e: (e.module, e.text)):
            lines.append(f"- `{entry.module}`: {entry.text}")
        if group:
            lines.append("")
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_glossary(entries: list[Entry]) -> str:
    by_term: dict[str, Entry] = {}
    for entry in entries:
        match = TERM_RE.match(entry.text)
        assert match is not None  # checked in _extract
        term = match.group("term").strip()
        key = term.casefold()
        if key in by_term:
            raise GenDocsError(f"term '{term}' is defined in both {by_term[key].path} and {entry.path}; keep one definition, in the package that owns the data")
        by_term[key] = entry
    lines = ["# Glossary", ""]
    if not by_term:
        lines.append("None yet.")
    for key in sorted(by_term):
        entry = by_term[key]
        match = TERM_RE.match(entry.text)
        assert match is not None
        lines.append(f"- **{match.group('term').strip()}** (`{entry.module}`): {match.group('definition').strip()}")
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_cujs(cujs: list[Cuj]) -> str:
    lines = ["# Critical user journeys", "", "Each journey is proven by the test named beside it.", ""]
    if not cujs:
        lines.append("None yet: mark end-to-end tests with `@pytest.mark.cuj(\"...\")`.")
    current_file = None
    for cuj in cujs:
        test_file = cuj.test_id.split("::", 1)[0]
        if test_file != current_file:
            if current_file is not None:
                lines.append("")
            lines += [f"## `{test_file}`", ""]
            current_file = test_file
        lines.append(f"- {cuj.journey} (`{cuj.test_id}`)")
    return HEADER + "\n".join(lines).rstrip() + "\n"


def generate(root: Path) -> dict[str, str]:
    """The generated files for the repo at `root`, as {path relative to root: text}."""
    cfg = load_config(root)
    areas, decisions, terms = _extract(root, cfg)
    out = Path(cfg.out)
    return {
        (out / "index.md").as_posix(): _render_index(areas, _uncovered(root, cfg)),
        (out / "decisions.md").as_posix(): _render_decisions(decisions),
        (out / "glossary.md").as_posix(): _render_glossary(terms),
        (out / "cujs.md").as_posix(): _render_cujs(sorted(_cujs(root, cfg) + _comment_cujs(root, cfg), key=lambda c: (c.test_id, c.journey))),
    }


def uncovered(root: Path) -> dict[str, int]:
    """Languages found under the source and test roots that the generator does not read: name -> file count."""
    return _uncovered(root, load_config(root))


def stale(root: Path) -> list[str]:
    """Generated files whose content on disk differs from what the code produces; writes nothing."""
    return sorted(rel for rel, text in generate(root).items() if _read(root / rel) != text)


def write(root: Path) -> list[str]:
    """Rewrite stale generated files atomically; return the ones changed."""
    files = generate(root)
    changed = []
    for rel in sorted(files):
        path = root / rel
        if _read(path) == files[rel]:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".tmp")
        tmp.write_text(files[rel])
        tmp.replace(path)
        changed.append(rel)
    return changed


def _read(path: Path) -> str | None:
    return path.read_text() if path.exists() else None
