"""Extraction and rendering for docs/generated/: pure over the files it reads.

`generate(root)` returns the four files as {relative path: text}; `write`
and `stale` compare that with what is on disk. Parsing failures raise
`GenDocsError` naming file and line, so a typo never silently drops an entry.
"""

from __future__ import annotations

import ast
import re
import tomllib
from dataclasses import dataclass
from pathlib import Path

HEADER = "<!-- Generated by metalm-gendocs from the code. Do not edit; change the docstring or test instead. -->\n\n"
OWNER_MARK = "(owner)"
SECTION_RE = re.compile(r"^(Decisions|Terms):\s*$")
NEVER_IMPORTS_RE = re.compile(r"^Never imports:\s*(.+)$")
TERM_RE = re.compile(r"^\*\*(?P<term>[^*]+)\*\*:\s*(?P<definition>.+)$", re.S)


class GenDocsError(Exception):
    """A docstring or marker the generator cannot read; the message names file and line."""


@dataclass(frozen=True, slots=True)
class Config:
    src: str = "src"
    tests: str = "tests"
    out: str = "docs/generated"


@dataclass(frozen=True, slots=True)
class Area:
    name: str
    path: str
    purpose: str
    never_imports: str


@dataclass(frozen=True, slots=True)
class Entry:
    """One bullet under Decisions: or Terms:, with where it came from."""

    module: str
    path: str
    text: str


@dataclass(frozen=True, slots=True)
class Cuj:
    journey: str
    test_id: str


def load_config(root: Path) -> Config:
    pyproject = root / "pyproject.toml"
    if not pyproject.exists():
        return Config()
    table = tomllib.loads(pyproject.read_text()).get("tool", {}).get("metalm-gendocs", {})
    known = set(Config.__dataclass_fields__)
    unknown = sorted(set(table) - known)
    if unknown:
        raise GenDocsError(f"pyproject.toml [tool.metalm-gendocs]: unknown key(s) {', '.join(unknown)}; known: {', '.join(sorted(known))}")
    for key, value in table.items():
        if not isinstance(value, str):
            raise GenDocsError(f"pyproject.toml [tool.metalm-gendocs].{key} must be a string")
    return Config(**table)


def _docstring(path: Path) -> str:
    try:
        tree = ast.parse(path.read_text(), filename=str(path))
    except SyntaxError as exc:
        raise GenDocsError(f"{path}:{exc.lineno}: cannot parse: {exc.msg}") from exc
    return ast.get_docstring(tree, clean=True) or ""


def _module_name(src_root: Path, path: Path) -> str:
    parts = list(path.relative_to(src_root).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _paragraph_one(doc: str) -> str:
    first = doc.strip().split("\n\n", 1)[0]
    return " ".join(first.split())


def _sections(doc: str) -> dict[str, list[str]]:
    """Bullets under each `Decisions:`/`Terms:` header; continuation lines join the bullet above."""
    out: dict[str, list[str]] = {}
    current: list[str] | None = None
    for line in doc.splitlines():
        stripped = line.strip()
        header = SECTION_RE.match(stripped)
        if header:
            current = out.setdefault(header.group(1), [])
        elif current is None:
            continue
        elif stripped.startswith("- "):
            current.append(stripped[2:].strip())
        elif stripped and current and line.startswith((" ", "\t")):
            current[-1] += " " + stripped
        else:
            current = None
    return out


def _sources(root: Path, cfg: Config) -> list[Path]:
    src_root = root / cfg.src
    if not src_root.is_dir():
        return []
    return sorted(p for p in src_root.rglob("*.py") if "__pycache__" not in p.parts)


def _is_area(src_root: Path, path: Path) -> bool:
    rel = path.relative_to(src_root).parts
    return path.name == "__init__.py" or len(rel) == 2


def _cuj_journey(decorator: ast.expr) -> ast.expr | None:
    """The journey argument when `decorator` is `pytest.mark.cuj(...)` or `mark.cuj(...)`; else None."""
    if not isinstance(decorator, ast.Call):
        return None
    func = decorator.func
    if not (isinstance(func, ast.Attribute) and func.attr == "cuj"):
        return None
    base = func.value
    if not (isinstance(base, ast.Attribute) and base.attr == "mark") and not (isinstance(base, ast.Name) and base.id == "mark"):
        return None
    return decorator.args[0] if decorator.args else ast.Constant(None)


def _cujs(root: Path, cfg: Config) -> list[Cuj]:
    tests_root = root / cfg.tests
    if not tests_root.is_dir():
        return []
    found: list[Cuj] = []
    for path in sorted(p for p in tests_root.rglob("test_*.py") if "__pycache__" not in p.parts):
        rel = path.relative_to(root).as_posix()
        try:
            tree = ast.parse(path.read_text(), filename=rel)
        except SyntaxError as exc:
            raise GenDocsError(f"{rel}:{exc.lineno}: cannot parse: {exc.msg}") from exc

        def visit(nodes: list[ast.stmt], prefix: str) -> None:
            for node in nodes:
                if isinstance(node, ast.ClassDef):
                    visit(node.body, f"{prefix}::{node.name}")
                if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                    continue
                for decorator in node.decorator_list:
                    arg = _cuj_journey(decorator)
                    if arg is None:
                        continue
                    if not (isinstance(arg, ast.Constant) and isinstance(arg.value, str) and arg.value.strip()):
                        raise GenDocsError(f"{rel}:{decorator.lineno}: cuj marker needs the journey as a plain string")
                    found.append(Cuj(" ".join(arg.value.split()), f"{prefix}::{node.name}"))

        visit(tree.body, rel)
    return sorted(found, key=lambda c: (c.test_id, c.journey))


def _extract(root: Path, cfg: Config) -> tuple[list[Area], list[Entry], list[Entry]]:
    src_root = root / cfg.src
    areas: list[Area] = []
    decisions: list[Entry] = []
    terms: list[Entry] = []
    for path in _sources(root, cfg):
        doc = _docstring(path)
        module = _module_name(src_root, path)
        rel = path.relative_to(root).as_posix()
        if _is_area(src_root, path):
            never = ""
            for line in doc.splitlines():
                match = NEVER_IMPORTS_RE.match(line.strip())
                if match:
                    never = match.group(1).strip()
            areas.append(Area(module, rel, _paragraph_one(doc), never))
        sections = _sections(doc)
        decisions += [Entry(module, rel, text) for text in sections.get("Decisions", [])]
        for text in sections.get("Terms", []):
            if not TERM_RE.match(text):
                raise GenDocsError(f"{rel}: Terms entry must read '- **term**: definition', got: {text[:60]}")
            terms.append(Entry(module, rel, text))
    return areas, decisions, terms


def _render_index(areas: list[Area]) -> str:
    lines = ["# Areas", ""]
    if not areas:
        lines.append("None yet: no packages under the source root.")
    for area in sorted(areas, key=lambda a: a.name):
        lines += [f"## `{area.name}`", "", f"`{area.path}`", "", area.purpose or "_No docstring._", ""]
        if area.never_imports:
            lines += [f"Never imports: {area.never_imports}", ""]
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_decisions(entries: list[Entry]) -> str:
    owner = [e for e in entries if e.text.rstrip().endswith(OWNER_MARK)]
    drafted = [e for e in entries if not e.text.rstrip().endswith(OWNER_MARK)]
    lines = ["# Decisions", "", "Rules that span modules, from each package's `Decisions:`. Owner rules end with `(owner)`.", ""]
    for title, group in (("Owner", owner), ("Agent-drafted", drafted)):
        lines += [f"## {title}", ""]
        if not group:
            lines += ["None yet.", ""]
        for entry in sorted(group, key=lambda e: (e.module, e.text)):
            lines.append(f"- `{entry.module}`: {entry.text}")
        if group:
            lines.append("")
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_glossary(entries: list[Entry]) -> str:
    by_term: dict[str, Entry] = {}
    for entry in entries:
        match = TERM_RE.match(entry.text)
        assert match is not None  # checked in _extract
        term = match.group("term").strip()
        key = term.casefold()
        if key in by_term:
            raise GenDocsError(f"term '{term}' is defined in both {by_term[key].path} and {entry.path}; keep one definition, in the package that owns the data")
        by_term[key] = entry
    lines = ["# Glossary", ""]
    if not by_term:
        lines.append("None yet.")
    for key in sorted(by_term):
        entry = by_term[key]
        match = TERM_RE.match(entry.text)
        assert match is not None
        lines.append(f"- **{match.group('term').strip()}** (`{entry.module}`): {match.group('definition').strip()}")
    return HEADER + "\n".join(lines).rstrip() + "\n"


def _render_cujs(cujs: list[Cuj]) -> str:
    lines = ["# Critical user journeys", "", "Each journey is proven by the test named beside it.", ""]
    if not cujs:
        lines.append("None yet: mark end-to-end tests with `@pytest.mark.cuj(\"...\")`.")
    current_file = None
    for cuj in cujs:
        test_file = cuj.test_id.split("::", 1)[0]
        if test_file != current_file:
            if current_file is not None:
                lines.append("")
            lines += [f"## `{test_file}`", ""]
            current_file = test_file
        lines.append(f"- {cuj.journey} (`{cuj.test_id}`)")
    return HEADER + "\n".join(lines).rstrip() + "\n"


def generate(root: Path) -> dict[str, str]:
    """The generated files for the repo at `root`, as {path relative to root: text}."""
    cfg = load_config(root)
    areas, decisions, terms = _extract(root, cfg)
    out = Path(cfg.out)
    return {
        (out / "index.md").as_posix(): _render_index(areas),
        (out / "decisions.md").as_posix(): _render_decisions(decisions),
        (out / "glossary.md").as_posix(): _render_glossary(terms),
        (out / "cujs.md").as_posix(): _render_cujs(_cujs(root, cfg)),
    }


def stale(root: Path) -> list[str]:
    """Generated files whose content on disk differs from what the code produces; writes nothing."""
    return sorted(rel for rel, text in generate(root).items() if _read(root / rel) != text)


def write(root: Path) -> list[str]:
    """Rewrite stale generated files atomically; return the ones changed."""
    files = generate(root)
    changed = []
    for rel in sorted(files):
        path = root / rel
        if _read(path) == files[rel]:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".tmp")
        tmp.write_text(files[rel])
        tmp.replace(path)
        changed.append(rel)
    return changed


def _read(path: Path) -> str | None:
    return path.read_text() if path.exists() else None
